#! /bin/bash

python3 assembler.py \
    --origin 0x0000 \
    --size 0x4000 \
    --destination bootrom.bin \
    --generate-symbols \
    --symbol-file bootrom.sym \
    lib/init.S \
    lib/math/neg.S \
    lib/math/abs.S \
    lib/math/add.S \
    lib/math/multiply.S \
    lib/math/divide.S \
    lib/math/cmp.S \
    lib/string/strcat.S \
    lib/string/strcpy.S \
    lib/string/strlen.S \
    lib/string/strcmp.S \
    lib/conversion/itoa.S \
    lib/conversion/atoi.S \
    lib/data.S
